### ISSUE TITLE
Q: Whether it would be possible that the expensive opearation is called twice (or more) for multithread

### ISSUE THREAD

**Issue by taooceros** [neon-sunset/fast-cache#50]
When checking the source code of `Cached.GetOrCompute`, it seems like we only do a very simple tryget or compute, without any synchronization. Will this result in multiple invocation of the expensive method?

**Comment by neon-sunset** [comment]
Hello @taooceros 
Locking onto the key would surprise the users as it is not the default behavior of the most popular caching libraries in C#. Additionally, it would incur overhead that goes against the design of this library (reads and writes are guaranteed to be lock-free and wait-free).

It would still not guard against multiple execution paths racing the computation of the value to store in the cache, since the cache can be accessed via `Cached.GetOrCompute(..)`, `Cached<V>.TryGet(...)` and `CachedRange<V>.Save(...)`.

In the case where you would like to ensure only exclusivity of cache value computation, this would have to be done in the user code.

Here's a snippet I wrote some time ago that prevents cache stampeding on a load test and provides the behavior you're looking for:
https://gist.github.com/neon-sunset/767cb0693c3ff222f78b236c9904a3fc#file-aspnetcoreexample-cs-L11-L40

**Comment by taooceros** [comment]
Hi, thanks for the detailed explanation! I am ok with the behavior as the method I am executing is a api request.

However I am a little bit concerned about the GetOrAdd method, as the name kindly implicitly suggests that it will only execute the delegate once, as our library are supposed to be thread safe. It might be possible that someone put a non thread safe delegate and results into data race error. I am very surprised that this is the default behavior of most c# caching library.

I personally advocate lockfree algorithm a lot, and thanks so much for such an interesting library.

**Comment by neon-sunset** [comment]
Thread-safety of delegate is not related to caching. In fact, standard `ConcurrentDictionary<K, V>.GetOrAdd(key, factory)` can and will race, with the factory delegate completing the execution last overwriting the value with of prior execution result.

If the code cannot be executed by multiple threads simultaneously, it means it it requires explicit synchronization, since the libraries that deal with caching or `Concurrent` collections cannot know this and are made for multi-threaded scenarios.

**Comment by neon-sunset** [comment]
@taooceros Does this address your initial concern? Let me know if you have any other questions.

**Comment by taooceros** [comment]
Thanks for explaining.
